/**
 * Mailer for GL Rule Assist
 *
 * Sends digest emails with pending AI-suggested rules.
 * Falls back to Ethereal test account if no SMTP env vars are set.
 */

const nodemailer = require('nodemailer');

async function getTransporter() {
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (host && user && pass) {
    return nodemailer.createTransport({
      host,
      port: parseInt(port) || 587,
      secure: false,
      auth: { user, pass }
    });
  }

  // Fallback to Ethereal test account
  console.log('📧 No SMTP configured — creating Ethereal test account...');
  const testAccount = await nodemailer.createTestAccount();
  console.log(`📧 Ethereal user: ${testAccount.user}`);
  return nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    auth: { user: testAccount.user, pass: testAccount.pass }
  });
}

function buildHtml(suggestions) {
  const cards = suggestions.map(s => `
    <div style="border:1px solid #e0e0e0; border-radius:8px; padding:16px; margin:12px 0; background:#fafafa;">
      <h3 style="margin:0 0 8px; color:#1a73e8;">GL ${s.suggestedGL} — ${s.suggestedPattern}</h3>
      <p style="margin:4px 0;"><strong>AI Reasoning:</strong> ${s.rationale}</p>
      <p style="margin:4px 0;"><strong>Affected Postings:</strong> ${s.affectedPostings}</p>
      <p style="margin:4px 0;"><strong>Sample Descriptions:</strong> ${s.sampleDescriptions}</p>
      <div style="margin-top:12px;">
        <a href="#approve-${s.unmatchedId}" style="background:#34a853; color:white; padding:8px 16px; border-radius:4px; text-decoration:none; margin-right:8px;">Approve</a>
        <a href="#reject-${s.unmatchedId}" style="background:#ea4335; color:white; padding:8px 16px; border-radius:4px; text-decoration:none;">Reject</a>
      </div>
    </div>
  `).join('');

  return `
    <div style="font-family:Arial,sans-serif; max-width:600px; margin:0 auto;">
      <h1 style="color:#1a73e8; border-bottom:2px solid #1a73e8; padding-bottom:8px;">
        GL Rule Assist — Weekly Digest
      </h1>
      <p>The following ${suggestions.length} AI-suggested rule(s) are pending review:</p>
      ${cards}
      <hr style="margin-top:24px;">
      <p style="color:#666; font-size:12px;">Generated by GL Rule Assist. Review and approve suggestions to improve automatic GL determination.</p>
    </div>
  `;
}

async function sendDigestEmail(to, suggestions) {
  const transporter = await getTransporter();
  const from = process.env.SMTP_FROM || 'gl-rule-assist@ncs.com';

  const info = await transporter.sendMail({
    from,
    to,
    subject: `GL Rule Assist — ${suggestions.length} Pending Suggestion(s)`,
    html: buildHtml(suggestions)
  });

  const previewUrl = nodemailer.getTestMessageUrl(info) || '';
  if (previewUrl) {
    console.log(`📧 Email preview: ${previewUrl}`);
  }
  console.log(`📧 Email sent: ${info.messageId}`);

  return {
    messageId: info.messageId,
    previewUrl: previewUrl || 'Check your inbox',
    suggestionsCount: suggestions.length,
    status: 'sent'
  };
}

module.exports = { sendDigestEmail };
